
    create table student.address (
        id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );

    create table student.course (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table student.customer (
        address_id bigint unique,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table student.department (
        id bigint generated by default as identity,
        department_name varchar(255),
        primary key (id)
    );

    create table student.employee (
        department_id bigint,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table student.home (
        price numeric(38,2),
        id bigint generated by default as identity,
        primary key (id)
    );

    create table student.home_room (
        home_id bigint not null,
        room_id bigint not null unique
    );

    create table student.room (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table student.student (
        id integer generated by default as identity,
        birth_of_date timestamp(6),
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (id)
    );

    create table student.student_course (
        student_id integer not null,
        course_id bigint not null,
        unique (student_id, course_id)
    );

    alter table if exists student.customer 
       add constraint FKglkhkmh2vyn790ijs6hiqqpi 
       foreign key (address_id) 
       references student.address;

    alter table if exists student.employee 
       add constraint FKbejtwvg9bxus2mffsm3swj3u9 
       foreign key (department_id) 
       references student.department;

    alter table if exists student.home_room 
       add constraint FKs9975spwhxi9l5sp63x21vrj6 
       foreign key (room_id) 
       references student.room;

    alter table if exists student.home_room 
       add constraint FKc42setb3gqgluc56w68ds32as 
       foreign key (home_id) 
       references student.home;

    alter table if exists student.student_course 
       add constraint FKejrkh4gv8iqgmspsanaji90ws 
       foreign key (course_id) 
       references student.course;

    alter table if exists student.student_course 
       add constraint FKq7yw2wg9wlt2cnj480hcdn6dq 
       foreign key (student_id) 
       references student.student;
