spring.config.import=optional:file:.env[.properties]
spring.application.name=spring-data-jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=student
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

#use spring.jpa.hibernate.ddl-auto=create at first run than change its value to "update"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.charset_name="UTF-8"
#spring.jpa.properties.hibernate.schema-generation.script.append=false
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 1. Hibernate should both apply the data to the database and write it to the file.
#also change database.action's value from "create" to "update" after first run
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create

# 2. Specify the exact location of the output files (next to pom.xml)
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop.sql

# 3. Use Java Entity classes as a source.
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.drop-source=metadata

# 4. Delay printing SQL data until after the table is created.
spring.jpa.defer-datasource-initialization=true
#use spring.sql.init.mode=never at first run than change its value to "always"
spring.sql.init.mode=always

app.servers[0].ip = 192.168.1.2
app.servers[0].location = Almanya

app.servers[1].ip = 192.168.2.2
app.servers[1].location = Fransa

app.servers[2].ip = 192.168.2.3
app.servers[2].location = ABD

key = 12345
